#!/usr/bin/env python3

from __future__ import print_function

import os

os.system("printf '\033]2;Unicorn Framework\a'")

import sys
import subprocess
import readline
import time
import socket

from os import environ
from core.badges import badges

badges = badges()

from core.unicat import server

def getip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("192.168.1.1", 80))
        host = s.getsockname()[0]
        s.close()
        host = host
    except:
        host = "127.0.0.1"
    return host

# Auto Complete input snippet

class MyCompleter(object):

    def __init__(self, options):
        self.options = sorted(options)

    def complete(self, text, state):
        if state == 0:
            if not text:
                self.matches = self.options[:]
            else:
                self.matches = [s for s in self.options
                                if s and s.startswith(text)]

        try:
            return self.matches[state]
        except IndexError:
            return None

    def display_matches(self, substitution, matches, longest_match_length):
        line_buffer = readline.get_line_buffer()
        columns = environ.get("COLUMNS", 80)

        print()

        tpl = "{:<" + str(int(max(map(len, matches)) * 1.2)) + "}"

        buffer = ""
        for match in matches:
            match = tpl.format(match[len(substitution):])
            if len(buffer + match) > columns:
                print(buffer)
                buffer = ""
            buffer += match

        if buffer:
            print(buffer)

        print("> ", end="")
        print(line_buffer, end="")
        sys.stdout.flush()


# Core Commands Autocomplete

core = [
    'clear',
    'exit',
    'help',
    'options',
    'run',
    'set',
    'update'
    ]

core = [x.split(' ')[0] for x in core]

completer = MyCompleter(list(set(core)))
readline.set_completer_delims(' \t\n;')
readline.set_completer(completer.complete)
readline.set_completion_display_matches_hook(completer.display_matches)
readline.parse_and_bind('tab: complete')

I = '\033[1;77m[i] \033[0m'
Q = '\033[1;77m[?] \033[0m'
S = '\033[1;32m[+] \033[0m'
W = '\033[1;33m[!] \033[0m'
E = '\033[1;31m[-] \033[0m'
G = '\033[1;34m[*] \033[0m'

def banner():
    os.system("clear")
    os.system("cat banner/banner.txt")
    print("")
    print("Unicorn Framework v1.0")
    print("----------------------")
    print("")

def main():
    lport = "4444"
    lhost = getip()
    try:
        ui = input('\033[4municorn\033[0m> ').strip(" ")
    except:
        sys.exit()
    ui = ui.split()
    while True:
        if ui == []:
            pass
        elif ui[0] == "exit":
            sys.exit()
        elif ui[0] == "clear":
            os.system("clear")
        elif ui[0] == "update":
            os.system("chmod +x etc/update.sh && etc/update.sh")
        elif ui[0] == "help":
            print("")
            print("Core Commands")
            print("=============")
            os.system("cat data/cmds/core_cmds.txt")
            print("")
        elif ui[0] == "options":
            if lhost == "":
                lhost = "none"
            if lport == "":
                lport = "none"
            os.system("ruby data/options/options.rb "+lhost+" "+lport)
        elif ui[0] == "set":
            if len(ui) < 3:
                print("Usage: set <option> <value>")
            else:
                if ui[1].lower() == "lhost":
                    lhost = ui[2]
                    print(badges.I + "LHOST ==> " + ui[2])
                elif ui[1].lower() == "lport":
                    lport = ui[2]
                    print(badges.I + "LPORT ==> " + ui[2])
                else:
                    print(badges.E +"Option is not found!")
        elif ui[0] == "run":
            if lhost == "" or lport == "":
                print(badges.E +"Failed to start listener!")
            else:
                #os.system("python3 core/unicat.py "+lhost+" "+lport)
                server(lhost, int(lport))
        else:
            print(badges.E +"Unrecognized command!")
        try:
            ui = input('\033[4municorn\033[0m> ').strip(" ")
        except:
            sys.exit()
        ui = ui.split()
        
banner()
main()
